<?php
$z[0]=Array("global","",222,249);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",322,349);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",352,378);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n      ",1068,1300);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>